title: Biblioteca Micologica
description: Catalogo della collezione del circolo
baseurl: ""
url: ""

markdown: kramdown

# IMPORTANT: Tell Jekyll not to use a theme
theme: null

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - scripts
  - README.md
  - LICENSE
  - .git
  - .github
  - .jekyll-cache
  - .jekyll-metadata