exclude:
  - aggiornamenti-nomenclatura/
  - biblioteca/
  - fungi-census/
  - vendor/
  - Gemfile
  - Gemfile.lock

# Tell Jekyll to treat your prebuilt folder as a static asset
keep_files:
  - aggiornamenti-nomenclatura/_site
  - biblioteca/_site
  - fungi-census/_site